[package]
name = "tile-xenium"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.3.24", features = ["derive"] }
polars = { version = "0.32.1", features = ["lazy", "strings"] }
