name: Rust

on:
  push:
    tags:
      - "v*.*.*"

env:
  CARGO_TERM_COLOR: always

jobs:
   build:
    runs-on: ubuntu-latest
    container: centos:7
    
    steps:
      - name: Install gcc
        run: |
          yum install gcc -y
        
      - name: Checkout
        uses: actions/checkout@v1

      - name: Install latest rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          default: true
          override: true

      - name: Build
        run: cargo build --release && strip target/release/tile-xenium

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            target/release/tile-xenium

